### ISSUE TITLE
WeeWX v4 Coming Soon Python 3.x

### ISSUE THREAD

**Issue by gary-hammer** [sprinkler/rainmachine-weewx#1]
Just wanted to say that this needed driver needs updated for the upcoming WeeWX 4 which runs with Python 3.x

I'd miss this if it is not updated.

**Comment by bigjools** [comment]
Yeah just got caught out by this. The source code is also a bit of a mess, the file has got mixed tabs and spaces for indentation. I'll try to get it working and submit a PR in the next few days.

**Comment by tkeffer** [comment]
I've already submitted a PR. Fixed the tabs. 

Give it a try.

**Comment by bigjools** [comment]
Checked it out just now and works great, thanks a bunch @tkeffer .

**Comment by gary-hammer** [comment]
Working well, thanks Tom!
